### ISSUE TITLE
zerotier-one.conf is missing because script deletes it before copying

### ISSUE THREAD

**Issue by xuijuthub** [ConzZah/ZeroTier_AutoCompile-Alpine#1]
https://github.com/ConzZah/ZeroTier_AutoCompile-Alpine/blob/6d4929dcbbc9a4e290da66b95502defc516e1de7/ZeroTier_AutoCompile-Alpine.sh#L12 `doas rm -rf ZeroTier_AutoCompile-Alpine`
https://github.com/ConzZah/ZeroTier_AutoCompile-Alpine/blob/6d4929dcbbc9a4e290da66b95502defc516e1de7/ZeroTier_AutoCompile-Alpine.sh#L14 `doas mv -f zerotier-one.conf /usr/lib/modules`

![VirtualBox_alpine-zerotier-one_21_09_2024_02_48_05](https://github.com/user-attachments/assets/914a9bad-eb33-402f-a599-b23657d1c177)

**Comment by ConzZah** [comment]
[fixed it](https://github.com/ConzZah/ZeroTier_AutoCompile-Alpine/commits/main/?since=2024-09-21&until=2024-09-21) & couldn't reproduce your issue  

![Screenshot from 2024-09-21 14-36-40](https://github.com/user-attachments/assets/3c46e1d9-9455-46f5-a64d-998d78d148d3)
