### ISSUE TITLE
bash is not on alpine by default, readme

### ISSUE THREAD

**Issue by xuijuthub** [ConzZah/ZeroTier_AutoCompile-Alpine#2]
`apk add bash`, but it would be better to make it not for bash, sh is enough for most scripts

**Comment by ConzZah** [comment]
agreeable, [i fixed it.](https://github.com/ConzZah/ZeroTier_AutoCompile-Alpine/commit/6c8b6050cf6a4a44b03c8b15495327dea8b87c7b)
