### ISSUE TITLE
compiled ok on 3.20.3 x86_64 virtual release

### ISSUE THREAD

**Issue by xuijuthub** [ConzZah/ZeroTier_AutoCompile-Alpine#4]
running virtualbox 6.1.50 r161033
vm config:
 linux x64 other
 512 MB RAM
 8 GB storage, of which 940 MB is swap
 1 virtual CPU
took over 10 minutes

`doas zerotier-cli join ............`
populates networks adapter, it works, no reboot was needed

**Comment by ConzZah** [comment]
nice
